apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plan-de-circulation.fullname" . }}-frontend
  labels:
    {{- include "plan-de-circulation.labels" . | nindent 4 }}
    component: frontend
  {{- with .Values.frontend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
  selector:
    matchLabels:
      {{- include "plan-de-circulation.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      labels:
        {{- include "plan-de-circulation.selectorLabels" . | nindent 8 }}
        component: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: 80
