apiVersion: v1
kind: Service
metadata:
  name: {{ include "plan-de-circulation.fullname" . }}-backend
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
  selector:
    {{- include "plan-de-circulation.selectorLabels" . | nindent 4 }}
    component: backend
